# Generated by Django 6.0.1 on 2026-02-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
