# Generated by Django 6.0.1 on 2026-02-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
